import type { Files } from "./lib/pyex";

export type Example = { name: string; blurb: string; code: string; files?: Files };

// NOTE: `code` strings are JS template literals. Inside them, a literal newline for a Python string
// must be written as \\n, and never put `$` immediately before `{` (it becomes JS interpolation).
// Every example here is run through the test harness (see /tmp/test_ex.ts) before shipping.

const ORDERS = JSON.stringify(
  [
    { id: 1, region: "us-east", total: 129.0, items: 2 },
    { id: 2, region: "eu-west", total: 89.5, items: 1 },
    { id: 3, region: "us-east", total: 340.0, items: 5 },
    { id: 4, region: "apac", total: 1200.0, items: 3 },
    { id: 5, region: "eu-west", total: 45.0, items: 1 },
    { id: 6, region: "us-east", total: 76.25, items: 2 },
    { id: 7, region: "apac", total: 560.0, items: 4 },
    { id: 8, region: "eu-west", total: 210.0, items: 2 },
    { id: 9, region: "us-east", total: 999.99, items: 7 },
    { id: 10, region: "apac", total: 42.0, items: 1 },
  ],
  null,
  2,
);

const APP_LOG =
  "2026-07-01 09:14:02.031 INFO  req=a1f2 GET /api/users 200 12ms\n" +
  "2026-07-01 09:14:03.104 INFO  req=b3c8 POST /api/orders 201 45ms\n" +
  "2026-07-01 09:14:04.210 WARN  req=c9d1 GET /api/search 200 812ms slow\n" +
  "2026-07-01 09:14:05.298 ERROR req=d4e7 POST /api/pay 500 23ms upstream timeout: payments-svc\n" +
  "2026-07-01 09:14:06.401 INFO  req=e5f9 GET /api/feed 200 34ms\n" +
  "2026-07-01 09:14:07.510 INFO  req=fa02 GET /api/users 200 9ms\n" +
  "2026-07-01 09:14:08.622 WARN  req=0b13 GET /api/search 200 1104ms slow\n" +
  "2026-07-01 09:14:09.733 ERROR req=1c24 POST /api/orders 500 41ms deadlock on orders_pkey\n" +
  "2026-07-01 09:14:10.844 INFO  req=2d35 DELETE /api/session 204 6ms\n" +
  "2026-07-01 09:14:11.955 INFO  req=3e46 POST /api/orders 201 52ms\n" +
  "2026-07-01 09:14:13.066 ERROR req=4f57 POST /api/pay 500 19ms upstream timeout: payments-svc\n" +
  "2026-07-01 09:14:14.177 INFO  req=5068 GET /api/feed 200 28ms\n" +
  "2026-07-01 09:14:15.288 WARN  req=6179 GET /api/search 200 934ms slow\n" +
  "2026-07-01 09:14:16.399 INFO  req=728a GET /api/users 200 11ms\n" +
  "2026-07-01 09:14:17.510 INFO  req=839b POST /api/orders 201 47ms\n" +
  "2026-07-01 09:14:18.621 ERROR req=94ac GET /api/search 500 71ms query planner OOM\n" +
  "2026-07-01 09:14:19.732 INFO  req=a5bd GET /api/feed 200 31ms\n" +
  "2026-07-01 09:14:20.843 INFO  req=b6ce DELETE /api/session 204 5ms\n";

export const EXAMPLES: Example[] = [
  {
    name: "data pipeline",
    blurb: "an ETL agent that instruments itself with OpenTelemetry",
    code: [
      "# An agent ETL pipeline — instrumented with OpenTelemetry, running on WasmGC.",
      "# The nested spans in the Trace panel are emitted by THIS Python code.",
      "from opentelemetry import trace",
      "import json",
      "",
      'tracer = trace.get_tracer("etl-agent")',
      "",
      'with tracer.start_as_current_span("pipeline") as root:',
      '    with tracer.start_as_current_span("extract") as s:',
      '        orders = json.loads(open("/data/orders.json").read())',
      '        s.set_attribute("orders", len(orders))',
      "",
      '    with tracer.start_as_current_span("transform") as s:',
      "        by_region = {}",
      "        for o in orders:",
      '            by_region.setdefault(o["region"], []).append(o["total"])',
      '        stats = {r: {"orders": len(v), "revenue": round(sum(v), 2)}',
      "                 for r, v in by_region.items()}",
      '        s.set_attribute("regions", len(stats))',
      "",
      '    with tracer.start_as_current_span("load") as s:',
      '        open("/out/by_region.json", "w").write(json.dumps(stats, indent=2))',
      '        s.set_attribute("path", "/out/by_region.json")',
      "",
      '    root.set_attribute("revenue", round(sum(o["total"] for o in orders), 2))',
      "",
      'print(f"{len(orders)} orders -> {len(stats)} regions")',
      "for r, st in sorted(stats.items()):",
      "    print(f\"  {r:8} {st['orders']:>2} orders   {st['revenue']:>9,.2f}\")",
    ].join("\n"),
    files: { "/data/orders.json": ORDERS },
  },
  {
    name: "log triage",
    blurb: "compute SLOs from a service log — traced end to end",
    code: [
      "# Agent task: triage a service log — compute SLOs, group errors, write reports.",
      "# Each phase is wrapped in an OpenTelemetry span (see the Trace panel).",
      "from opentelemetry import trace",
      "import json",
      "",
      'tracer = trace.get_tracer("triage")',
      "",
      'with tracer.start_as_current_span("parse") as s:',
      "    reqs = []",
      '    for ln in open("/logs/app.log").read().splitlines():',
      "        p = ln.split()",
      "        if len(p) < 8:",
      "            continue",
      '        reqs.append({"level": p[2], "method": p[4], "path": p[5],',
      '                     "status": int(p[6]), "latency": int(p[7].rstrip("ms")),',
      '                     "msg": " ".join(p[8:])})',
      '    s.set_attribute("requests", len(reqs))',
      "",
      'with tracer.start_as_current_span("analyze") as s:',
      '    errors = [r for r in reqs if r["status"] >= 500]',
      '    lat = sorted(r["latency"] for r in reqs)',
      "    p50 = lat[len(lat) // 2]",
      "    p95 = lat[min(len(lat) - 1, int(len(lat) * 0.95))]",
      "    by_path = {}",
      "    for r in reqs:",
      '        by_path[r["path"]] = by_path.get(r["path"], 0) + 1',
      '    s.set_attribute("errors", len(errors))',
      '    s.set_attribute("p95_ms", p95)',
      "",
      'with tracer.start_as_current_span("write_reports"):',
      '    metrics = {"requests": len(reqs), "errors": len(errors),',
      '               "error_rate": round(len(errors) / len(reqs), 3), "p50_ms": p50, "p95_ms": p95}',
      '    open("/reports/metrics.json", "w").write(json.dumps(metrics, indent=2))',
      '    open("/reports/errors.log", "w").write(',
      "        \"\\n\".join(f\"{r['method']} {r['path']} -> {r['status']}  {r['msg']}\" for r in errors))",
      "",
      'print(f"{len(reqs)} requests, {len(errors)} errors ({metrics[\'error_rate\']:.1%}), p95 {p95}ms")',
      "for path, n in sorted(by_path.items(), key=lambda kv: -kv[1])[:4]:",
      '    print(f"  {path:16} {n:>2} requests")',
    ].join("\n"),
    files: { "/logs/app.log": APP_LOG, "/reports/.keep": "" },
  },
  {
    name: "codemod",
    blurb: "rename a function across a codebase, in place",
    code: [
      "# Agent task: rename a function across the whole codebase, in place.",
      "# Watch the Files panel: the sources are rewritten. Watch the Trace: a read + write",
      "# span per file, plus the agent's own scan/apply spans.",
      "from opentelemetry import trace",
      "",
      'tracer = trace.get_tracer("codemod")',
      'OLD, NEW = "get_user", "fetch_user"',
      'sources = ["/src/models.py", "/src/handlers.py", "/src/service.py", "/src/main.py"]',
      "",
      "changed = []",
      "for path in sources:",
      '    with tracer.start_as_current_span("rewrite") as s:',
      '        s.set_attribute("file", path)',
      "        text = open(path).read()",
      "        if OLD in text:",
      "            n = text.count(OLD)",
      '            with open(path, "w") as f:',
      "                f.write(text.replace(OLD, NEW))",
      "            changed.append((path, n))",
      '            s.set_attribute("occurrences", n)',
      "",
      'print(f"renamed {OLD}() -> {NEW}() in {len(changed)} of {len(sources)} files")',
      "for path, n in changed:",
      '    print(f"  {path:18} {n} occurrences")',
    ].join("\n"),
    files: {
      "/src/models.py": "def get_user(uid):\n    return db.query(uid)\n",
      "/src/handlers.py": "from models import get_user\n\ndef handle(req):\n    return get_user(req.uid).name\n",
      "/src/service.py": "from models import get_user\n\ndef enrich(uid):\n    u = get_user(uid)\n    return {'id': uid, 'name': u.name}\n",
      "/src/main.py": "print('starting')\n# no user lookup in this file\n",
    },
  },
  {
    name: "search index",
    blurb: "read every doc, build an inverted index",
    code: [
      "# Agent task: read every doc in the workspace and build an inverted search index.",
      "# One read span per document (a clean fan-in in the Trace panel), then a single write.",
      "from opentelemetry import trace",
      "import json",
      "",
      'tracer = trace.get_tracer("indexer")',
      'docs = ["/docs/intro.md", "/docs/api.md", "/docs/faq.md", "/docs/perf.md"]',
      "",
      "index = {}",
      'with tracer.start_as_current_span("index") as root:',
      "    for path in docs:",
      "        text = open(path).read().lower()",
      '        name = path.split("/")[-1]',
      "        for word in text.split():",
      '            w = "".join(c for c in word if c.isalnum())',
      "            if len(w) < 3:",
      "                continue",
      "            index.setdefault(w, []).append(name)",
      '    root.set_attribute("terms", len(index))',
      "",
      "out = {w: sorted(set(docs)) for w, docs in index.items()}",
      'open("/index.json", "w").write(json.dumps(out, indent=2, sort_keys=True))',
      "",
      'print(f"indexed {len(docs)} docs, {len(index)} unique terms")',
      'for term in ["python", "webassembly", "sandbox", "fast"]:',
      "    hits = out.get(term)",
      "    print(f\"  {term:12} -> {hits if hits else '(no hits)'}\")",
    ].join("\n"),
    files: {
      "/docs/intro.md": "pyex is a Python interpreter written in Elixir. It runs in a sandbox.",
      "/docs/api.md": "The pyex API exposes run and a virtual filesystem for agent workloads.",
      "/docs/faq.md": "Is it fast? pyex compiles to WebAssembly. Is it safe? Yes, every agent runs sandboxed.",
      "/docs/perf.md": "Startup is fast: the interpreter loads once, then each run is sub-millisecond.",
    },
  },
  {
    name: "lru cache",
    blurb: "the one they always ask you to whiteboard",
    code: [
      "# You know the one. O(1) get and put — hash map + doubly linked list.",
      "# (No, we will not be using an OrderedDict. We have standards.)",
      "class Node:",
      "    def __init__(self, k=None, v=None):",
      "        self.k = k",
      "        self.v = v",
      "        self.prev = None",
      "        self.next = None",
      "",
      "class LRUCache:",
      "    def __init__(self, capacity):",
      "        self.cap = capacity",
      "        self.map = {}",
      "        self.head = Node()              # most-recently-used sentinel",
      "        self.tail = Node()              # least-recently-used sentinel",
      "        self.head.next = self.tail",
      "        self.tail.prev = self.head",
      "",
      "    def _remove(self, n):",
      "        n.prev.next = n.next",
      "        n.next.prev = n.prev",
      "",
      "    def _push_front(self, n):",
      "        n.next = self.head.next",
      "        n.prev = self.head",
      "        self.head.next.prev = n",
      "        self.head.next = n",
      "",
      "    def get(self, key):",
      "        if key not in self.map:",
      "            return -1",
      "        n = self.map[key]",
      "        self._remove(n)",
      "        self._push_front(n)",
      "        return n.v",
      "",
      "    def put(self, key, value):",
      "        if key in self.map:",
      "            self._remove(self.map[key])",
      "        n = Node(key, value)",
      "        self.map[key] = n",
      "        self._push_front(n)",
      "        if len(self.map) > self.cap:",
      "            lru = self.tail.prev",
      "            self._remove(lru)",
      "            del self.map[lru.k]",
      "",
      "cache = LRUCache(2)",
      'ops = [("put", 1, 1), ("put", 2, 2), ("get", 1), ("put", 3, 3),',
      '       ("get", 2), ("put", 4, 4), ("get", 1), ("get", 3), ("get", 4)]',
      "for op in ops:",
      '    if op[0] == "put":',
      "        cache.put(op[1], op[2])",
      '        print(f"put({op[1]}, {op[2]})")',
      "    else:",
      '        print(f"get({op[1]}) -> {cache.get(op[1])}")',
    ].join("\n"),
  },
];
